/*
 * Pictures.h
 *
 *  Created on: 24-Jun-2022
 *      Author: hp
 */

#ifndef INC_PICTURES_H_
#define INC_PICTURES_H_

#define B	BLACK
#define W	PURPLE

const uint16_t left_arrow[] = {
/*Pixel format: Red: 3 bit, Green: 3 bit, Blue: 2 bit*/
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, W, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, W, W, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
		B, B, B, B, B, B, B, B, B, B, W, W, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, W, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, W, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, W, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
		B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, };


//const unsigned int temperature_icon_40x40[] = {
//B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, B, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, B, W, W,
//		B, B, B, B, B, B, B, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, B, W, W, W,
//		B, B, B, B, B, B, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, B, W, W, W, W,
//		B, B, B, B, B, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, B, W, W, W, W, W,
//		B, B, B, B, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, B, B, W, W, W, W, W, W,
//		B, B, B, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, W, W, W,
//		B, B, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, W, W, W, W, W, W, W, W, W,
//		B, W, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, W,
//		W, W, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, W, W, W, W, W, W, W, W, W, B,
//		B, W, W, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, W, W, W, W, W, W, W, B, B,
//		B, B, W, W, W, W, W, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B,
//		B, B, B, B, B, B, B, B, W, W, W, W, W, B, B, B,
//
//};

#endif /* INC_PICTURES_H_ */
